### ISSUE TITLE
Beginner question, where do I correct my current meter reading?

### ISSUE THREAD

**Issue by thrusty66** [zibous/ha-gasmeter#3]
I have tried a few things, but have not come to a positive result. Where can I correct the counter reading? At which position do I have to enter a correction?

So if e.g. my reed has bounced again.
I use the init project without watter and dallas...

**Comment by zibous** [comment]
hi,

do you use this ?
https://github.com/zibous/ha-gasmeter/blob/main/gasmeter.yaml

You also use the resistor ? 
Without this, the pulse counting did not always work for me.

You can use the filters on the binary sensor to turn off the bouncing.

```yaml
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode: INPUT_PULLUP
      inverted: false
    filters:
      - delayed_on: 50ms
      - delayed_off: 50ms  
    name: ${device_name_upper} Gaszähler Z-61 Impuls
    id: gassensor_state
    device_class: window
    filters:
      - delayed_off: 10ms
    on_release:
      then:
        - lambda: |-
            id(z61counter) += ${impulsfactor};
            id(z61count) += 1;
            id(gas_meter_totalm3) += ${impulsfactor};
            id(gas_meter_displayvalue) += ${impulsfactor};
            id(daily_value) += ${impulsfactor};
            id(gas_meter_display).update();
            id(gas_meter_total_m3).update();
            id(gas_meter_total_kw).update();
            id(gas_meter_total_kw_day).update();
      
```

> Where can I correct the counter reading? At which position do I have to enter a correction?

Sometimes my ESP boots and can't count any impulses so that I have the right meter reading, I have to correct it. 
Or if I flash the new firmware and the ESP is offline for a long time...

![Bildschirmfoto 2022-11-21 um 13 20 25](https://user-images.githubusercontent.com/30198737/203053462-af355ee1-e49b-45e2-9abf-393f1f781d7a.png)
